name: quality

on:
  pull_request:
  push:
    branches:
      - "master"
  schedule:
    - cron: "17 4 * * 1"
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  security-events: write

jobs:
  quality:
    uses: EnVisione/.github/.github/workflows/quality.yml@main
    with:
      java-version: "21"
      gradle-enabled: false
      gradle-tasks: "check build"
      gametest-tasks: ""
      node-enabled: true
      node-version: "22"
      codeql-languages: '["javascript-typescript"]'
      native-security: true
      enforce-docs-layout: false
